#Dissecando uma Variável (is)
n=input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('Só tem espaços?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Esta em maiúscula?', n.isupper())
print('Esta em minúscula', n.islower())
print('Esta capitalizada?', n.istitle())
